// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCM96vgjMT_dEKSveMp0Z9tK0crYeFuc8',
    appId: '1:998489221180:web:62d53e3722f951bec57b39',
    messagingSenderId: '998489221180',
    projectId: 'daleelak-lb',
    authDomain: 'daleelak-lb.firebaseapp.com',
    storageBucket: 'daleelak-lb.appspot.com',
    measurementId: 'G-KQHFDZWHW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPHtngSt4GG49cAX7xGRC89I80f70zF8s',
    appId: '1:998489221180:android:fb41263f4116f2b4c57b39',
    messagingSenderId: '998489221180',
    projectId: 'daleelak-lb',
    storageBucket: 'daleelak-lb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAar6sS_g7yt7JhmrX3SRXip5kIfflAix0',
    appId: '1:998489221180:ios:a4ad31c8a8cc88b4c57b39',
    messagingSenderId: '998489221180',
    projectId: 'daleelak-lb',
    storageBucket: 'daleelak-lb.appspot.com',
    iosBundleId: 'com.dalilak.dalilakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAar6sS_g7yt7JhmrX3SRXip5kIfflAix0',
    appId: '1:998489221180:ios:a4ad31c8a8cc88b4c57b39',
    messagingSenderId: '998489221180',
    projectId: 'daleelak-lb',
    storageBucket: 'daleelak-lb.appspot.com',
    iosBundleId: 'com.dalilak.dalilakApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCM96vgjMT_dEKSveMp0Z9tK0crYeFuc8',
    appId: '1:998489221180:web:99f368391fb043e1c57b39',
    messagingSenderId: '998489221180',
    projectId: 'daleelak-lb',
    authDomain: 'daleelak-lb.firebaseapp.com',
    storageBucket: 'daleelak-lb.appspot.com',
    measurementId: 'G-W8QF4K45EV',
  );
}
